@startuml

class Juego {
- nombre 
+Iniciar()
+Terminar()
}

class Ronda {
- numero
+Iniciar()
+Terminar()
}

class Nivel {
- nombre
+Elegir()
}

class Tiempo {
- segundos
+Restar()
}

class Escenario {
- nombre
+Cambiar()
}

class Item {
- tipo
+Usar()
}

class Personaje {
- Vida porcentaje[0..100]
+Atacar()
+Defender()
+UsarHyper()
}

class Spiderman {
- tela
+Telaraña()
}

class Ryu {
- energia
+Hadouken()
}

class Ken {
- fuego
+Shoryuken()
}

class ChunLi {
- velocidad
+Patada()
}

class Jugador {
- nombre
+ElegirPersonaje()
}

class Equipo {
- miembros
+Agregar()
+Quitar()
}

class Vida {
- porcentaje
+Perder()
+Recuperar()
}

class Energia {
- nivel
+Gastar()
+Recuperar()
}

class Puntos {
- valor
+Sumar()
}

class BarraHyper {
- carga
+Cargar()
+Usar()
}

class Estado {
- nombre
+Poner()
+Quitar()
}

class Movimiento {
- nombre
+Ejecutar()
}

class MovimientoEspecial {
- nombre
+EjecutarEspecial()
}

class SuperMovimiento {
- nombre
- superPoder
+EjecutarSuper()
}

class Combo {
- pasos
+HacerCombo()
}

class Golpe {
- fuerza
+Impactar()
}

class Ataque {
- potencia
+Dañar()
}

class Defensa {
- nivel
+Bloquear()
}

class Salto {
- altura
+Saltar()
}

class Proyectil {
- velocidad
+Lanzar()
}

class Dano {
- cantidad
+Calcular()
}






class Poder {
- nombre
+Activar()
}

class Victoria {
- ganador
+Celebrar()
}

class Derrota {
- perdedor
+Mostrar()
}



class Asistencia {
- movimientoPredefinido
- usosRestantes[0..n]
+ MovimientoEspecial: Golpear()
+ MovimientoEspecial: Cubrir()
+ Invocar()
}

Spiderman --|> Personaje
Ryu --|> Personaje
Ken --|> Personaje
ChunLi --|> Personaje

Jugador --|> Personaje

MovimientoEspecial --|> Movimiento
SuperMovimiento --|> Movimiento
Golpe --|> Ataque


Personaje "1" o-- "1..*" Asistencia

Juego "1" *-- "1..*" Ronda
Juego "1" *-- "1" Tiempo
Juego "1" *-- "*" Nivel
Juego "1" *-- "*" Escenario
Juego "1" *-- "1..2" Jugador

Jugador "1" *-- "1" Equipo
Equipo "1" *-- "2..3" Personaje

Escenario "1" *-- "0..*" Item
Escenario "1" *-- "*" Colision

Personaje "1" *-- "1" Vida
Personaje "1" *-- "1" Energia
Personaje "1" *-- "0..1" Puntos
Personaje "1" *-- "0..1" BarraHyper
Personaje "1" *-- "*" Estado
Personaje "1" *-- "0..*" Poder
Personaje "1" *-- "0..*" Animacion
Personaje "1" *-- "1..*" Hitbox
Personaje "1" *-- "0..*" Movimiento
Personaje "1" *-- "0..*" Combo
Personaje "1" *-- "0..*" Asistencia
Personaje "1" *-- "0..*" Defensa
Personaje "1" *-- "0..*" Salto
Personaje "1" *-- "0..*" Item

Ataque "1" *-- "1" Dano
Ataque "1" *-- "0..1" Proyectil

Movimiento "1" *-- "0..*" Golpe
Movimiento "1" *-- "0..*" Colision

Ronda "1" *-- "0..1" Victoria
Ronda "1" *-- "0..1" Derrota
@enduml