class Juego
class Ronda
class Nivel
class Tiempo
class Escenario
class Interfaz
class Sonido
class Musica

class Personaje
class Spiderman
class Jugador
class CPU
class Equipo

class Vida
class Energia
class Puntaje
class BarraEspecial
class Estado

class Movimiento
class MovimientoEspecial
class SuperMovimiento
class Combo
class Golpe
class Ataque
class Defensa
class Salto
class Proyectil
class Daño
class Colision
class Hitbox
class Animacion
class Poder

class Victoria
class Derrota

class Control
class Item

' --- herencias ---
Spiderman --|> Personaje
Ryu --|> Personaje
Ken --|> Personaje
ChunLi --|> Personaje

Jugador --|> Personaje
CPU --|> Personaje

MovimientoEspecial --|> Movimiento
SuperMovimiento --|> Movimiento

' --- asociaciones con multiplicidad ---
Juego "1" *-- "1..*" Ronda
Juego "1" *-- "1" Tiempo
Juego "1" *-- "*" Nivel
Juego "1" *-- "*" Escenario
Juego "1" *-- "*" Jugador
Juego "1" *-- "0..*" Equipo
Juego "1" *-- "1" Interfaz
Juego "1" *-- "1" Sonido
Juego "1" *-- "0..*" Musica

Jugador "1" *-- "1" Control
Equipo "1" *-- "*" Personaje

Escenario "1" *-- "0..*" Item
Escenario "1" *-- "*" Colision

Personaje "1" *-- "1" Vida
Personaje "1" *-- "1" Energia
Personaje "1" *-- "0..1" Puntaje
Personaje "1" *-- "0..1" BarraEspecial
Personaje "1" *-- "*" Estado
Personaje "1" *-- "0..*" Poder
Personaje "1" *-- "0..*" Animacion
Personaje "1" *-- "1..*" Hitbox
Personaje "1" *-- "0..*" Movimiento
Personaje "1" *-- "0..*" Combo
Personaje "1" *-- "0..*" Ataque
Personaje "1" *-- "0..*" Defensa
Personaje "1" *-- "0..*" Salto
Personaje "1" *-- "0..*" Item

Ataque "1" *-- "1" Daño
Ataque "1" *-- "0..1" Proyectil

Movimiento "1" *-- "0..*" Golpe
Movimiento "1" *-- "0..*" Colision

Ronda "1" *-- "0..1" Victoria
Ronda "1" *-- "0..1" Derrota